### ISSUE TITLE
run.bash not pulled from dockerhub

### ISSUE THREAD

**Issue by eferreirafilho** [osrf/icra2023_ros2_gz_tutorial#31] opened 2023-05-26 14:31 UTC
Followed instructions from: Option 1: Pull from DockerHub (recommended) but when running :

```
 ./run.bash osrf/icra2023_ros2_gz_tutorial:tutorial_nvidia
```
was getting
```
 ./run.bash: command not found
```

Manually getting run.bash (and chmod +x it) from your repo solved the issue

**Comment by mabelzhang** [comment] 2023-05-26 15:27
Hi, that is working as intended. DockerHub contains the Docker image, but you need to clone this GitHub repository to get the run.bash in order to run the Docker image. It does not work to have the run.bash inside the Docker image, because that file is needed outside the image, on the host machine, in order to run the image.

Does that make sense?

I'm going to close this ticket as resolved. Feel free to reopen if you have a related followup question.

**Closed by mabelzhang** 2023-05-26 15:27 UTC
